[package]
name = "gpms-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.188", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }